### PR TITLE
added transparency for tb.copyFrom

### PR DESCRIPTION
**Pull request by marwal-88**
Minimal changes - per request.

### CODE REVIEW

**Review by johnnovak — APPROVED** [review]
Sorry @marwal-88, was kinda busy in the last couple of days and forgot about it... This looks good! Could you please also add that nice little test you've shown me? Thanks!

**Comment by marwal-88** [comment]
Thanx. Will do later today (will be tomorrow morning in Australia).

**Comment by marwal-88** [comment]
Added transparency.nim to /example

**Comment by johnnovak** [comment]
Thanks @marwal-88 , great job 👍🏻

**Pull request merged**
