### PR TITLE
✨ Added a GitHub Actions pipeline for generating docs

### PR DESCRIPTION
**Pull request by hitblast**
### This PR adds:

- A new workflow file inside the .github directory which uses the pre-included `docgen` task to generate the documentation for illwill, then automatically deploy a GitHub Pages site by uploading the generated static files as artifacts.

### Live Demo

A preview is hosted on my fork: https://hitblast.github.io/illwill

### Why?

I found this technique useful for some of my previous projects with and/or without Nim, and since this project was missing a documentation webpage, I thought it'd be useful to add one manually.

⚠️ **Must enable GitHub Pages inside the project settings and select "GitHub Actions" as source.**

### CODE REVIEW

**Comment by johnnovak** [comment]
Hey @hitblast, this seems interesting, thanks. Can you please point me to the generated GitHub pages using your branch? Just want to preview how it looks like before I merge this 😄

**Comment by hitblast** [comment]
> Hey @hitblast, this seems interesting, thanks. Can you please point me to the generated GitHub pages using your branch? Just want to preview how it looks like before I merge this 😄 

@johnnovak Hello! I've already mentioned the link to the preview that I've hosted, but here you go:

https://hitblast.github.io/illwill

The workflow looks like this:

https://github.com/hitblast/illwill/actions/runs/8355163831

Feel free to have a look! :D

**Comment by johnnovak** [comment]
> @johnnovak Hello! I've already mentioned the link to the preview that I've hosted, but here you go:

Ah, my bad, getting tired. 

Thanks for this, merging 🚀

**Comment by hitblast** [comment]
> Ah, my bad, getting tired. 
> 
> Thanks for this, merging 🚀

Thanks for the merge! :D

**Pull request merged**
